// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entidades.Empresa", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("AfiliacionIva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEmpresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Regimen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representante")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.Marca", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.Permiso", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Codigo");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.Rol", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Codigo");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.RolPermiso", b =>
                {
                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("Permiso")
                        .HasColumnType("int");

                    b.Property<int>("Busqueda")
                        .HasColumnType("int");

                    b.Property<int>("Insertar")
                        .HasColumnType("int");

                    b.Property<int>("Reimpresion")
                        .HasColumnType("int");

                    b.HasKey("Rol", "Permiso");

                    b.HasIndex("Permiso");

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.Sucursale", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoSucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoCopia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("EmpresaCodigo")
                        .HasColumnType("int");

                    b.Property<string>("Encargado")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("LlaveFirma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlaveSucursal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LLaveSucursal");

                    b.Property<int?>("Municipio")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.HasIndex(new[] { "EmpresaCodigo" }, "IX_Sucursales_EmpresaCodigo");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Backend.Entidades.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("FechaRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Foto")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Codigo");

                    b.HasIndex("Rol");

                    b.HasIndex(new[] { "Usuario1" }, "IX_Usuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.UsuarioEmpSuc", b =>
                {
                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Sucursal")
                        .HasColumnType("int");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int?>("UsuarioRegistro")
                        .HasColumnType("int");

                    b.HasKey("Usuario", "Sucursal")
                        .HasName("PK_UsuarioEmpSuc_1");

                    b.HasIndex("Sucursal");

                    b.ToTable("UsuarioEmpSuc", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.UsuarioPermiso", b =>
                {
                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Permiso")
                        .HasColumnType("int");

                    b.Property<int>("Busqueda")
                        .HasColumnType("int");

                    b.Property<int>("Insertar")
                        .HasColumnType("int");

                    b.Property<int>("Reimpresion")
                        .HasColumnType("int");

                    b.HasKey("Usuario", "Permiso");

                    b.HasIndex("Permiso");

                    b.ToTable("UsuarioPermiso", (string)null);
                });

            modelBuilder.Entity("Backend.Entidades.RolPermiso", b =>
                {
                    b.HasOne("Backend.Entidades.Permiso", "PermisoNavigation")
                        .WithMany("RolPermisos")
                        .HasForeignKey("Permiso")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Permiso");

                    b.HasOne("Backend.Entidades.Rol", "RolNavigation")
                        .WithMany("RolPermisos")
                        .HasForeignKey("Rol")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Rol");

                    b.Navigation("PermisoNavigation");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("Backend.Entidades.Sucursale", b =>
                {
                    b.HasOne("Backend.Entidades.Empresa", "EmpresaCodigoNavigation")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaCodigoNavigation");
                });

            modelBuilder.Entity("Backend.Entidades.Usuario", b =>
                {
                    b.HasOne("Backend.Entidades.Rol", "RolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Rol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("Backend.Entidades.UsuarioEmpSuc", b =>
                {
                    b.HasOne("Backend.Entidades.Sucursale", "SucursalNavigation")
                        .WithMany("UsuarioEmpSucs")
                        .HasForeignKey("Sucursal")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioEmpSuc_Sucursales");

                    b.HasOne("Backend.Entidades.Usuario", "UsuarioNavigation")
                        .WithMany("UsuarioEmpSucs")
                        .HasForeignKey("Usuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioEmpSuc_Usuario");

                    b.Navigation("SucursalNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("Backend.Entidades.UsuarioPermiso", b =>
                {
                    b.HasOne("Backend.Entidades.Permiso", "PermisoNavigation")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("Permiso")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioPermiso_Permiso");

                    b.HasOne("Backend.Entidades.Usuario", "UsuarioNavigation")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("Usuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioPermiso_Usuario");

                    b.Navigation("PermisoNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("Backend.Entidades.Empresa", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Backend.Entidades.Permiso", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("Backend.Entidades.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Backend.Entidades.Sucursale", b =>
                {
                    b.Navigation("UsuarioEmpSucs");
                });

            modelBuilder.Entity("Backend.Entidades.Usuario", b =>
                {
                    b.Navigation("UsuarioEmpSucs");

                    b.Navigation("UsuarioPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
